### ISSUE TITLE
Some plots fail with a NullPointerException

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1231]
Some combinations of plot variables (often variable vs variable) fail with an exception:

```
java.lang.NullPointerException
	at uk.ac.exeter.QuinCe.web.PlotPage.Data.PlotPageData.getClosestWithField(PlotPageData.java:211)
	at uk.ac.exeter.QuinCe.web.PlotPage.Data.PlotPageData.getPlotDataWithNonIdAxis(PlotPageData.java:198)
	at uk.ac.exeter.QuinCe.web.PlotPage.Data.PlotPageData.getPlotData(PlotPageData.java:100)
	at uk.ac.exeter.QuinCe.web.PlotPage.Plot.updatePlot(Plot.java:247)
```

**Comment by squaregoldfish** [comment]
This occurs when you plot variables with zero overlap, e.g. Marine fCO₂ vs Atmospheric CO₂

**Comment by MarenKK** [comment]
#249
