### ISSUE TITLE
Intermittent error in extracting data sets

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1328]
Some run type handling at the end of datasets fails because it falls off the end.

```
Dataset Extraction - error: Index: 1022, Size: 1022

java.lang.IndexOutOfBoundsException: Index: 1022, Size: 1022
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at uk.ac.exeter.QuinCe.jobs.files.ExtractDataSetJob.execute(ExtractDataSetJob.java:225)
at uk.ac.exeter.QuinCe.jobs.JobThread.run(JobThread.java:79)
```

**Comment by squaregoldfish** [comment]
Triggered with Nuka Arctica dataset starting 2019-086 and ending 2019-108

**Comment by squaregoldfish** [comment]
This was due to not ordering records as they are extracted from the database and subsequently processed.
