### ISSUE TITLE
Issue with Nuka data and standards

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1340]
Pretty normal data set covering multiple days with standard records. For some reason they're not being found for STD2:

```
uk.ac.exeter.QuinCe.jobs.JobFailedException: Job ID 717 failed
	at uk.ac.exeter.QuinCe.jobs.files.DataReductionJob.execute(DataReductionJob.java:229)
	at uk.ac.exeter.QuinCe.jobs.JobThread.run(JobThread.java:79)
Caused by: uk.ac.exeter.QuinCe.data.Dataset.DataReduction.DataReductionException: Error while applying internal calibration
	at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.DataReducer.applyValueCalibration(DataReducer.java:397)
	at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.UnderwayMarinePco2Reducer.doCalculation(UnderwayMarinePco2Reducer.java:78)
	at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.DataReducer.performDataReduction(DataReducer.java:113)
	at uk.ac.exeter.QuinCe.jobs.files.DataReductionJob.execute(DataReductionJob.java:169)
	... 1 more
Caused by: uk.ac.exeter.QuinCe.utils.RecordNotFoundException: No calibrations found for external standard 'std2'
	at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.DataReducer.calculateStandardValueAtDate(DataReducer.java:425)
	at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.DataReducer.applyValueCalibration(DataReducer.java:381)
	... 4 more
```

**Comment by squaregoldfish** [comment]
The gas standard measurements aren't being extracted for Nuka, while they are for BS. 🤔
