### ISSUE TITLE
Pressing Finish button on non-NRT data set throws an error

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1462]
Everything works as it should, but the following is logged:

```
org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: Error reading [nrt] on type [uk.ac.exeter.QuinCe.web.datasets.plotPage.ManualQC.ManualQcBean]
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:104)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:377)
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:1211)
	at org.apache.myfaces.view.facelets.tag.ui.ComponentRef.isRendered(ComponentRef.java:47)
	at javax.faces.component.UIComponentBase._isPhaseExecutable(UIComponentBase.java:2440)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1489)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1498)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1505)
	at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1505)
	at javax.faces.component.UIViewRoot._processUpdatesDefault(UIViewRoot.java:1694)
	at javax.faces.component.UIViewRoot.access$700(UIViewRoot.java:77)
	at javax.faces.component.UIViewRoot$UpdateModelPhaseProcessor.process(UIViewRoot.java:1832)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1655)
	at javax.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:916)
	at org.apache.myfaces.lifecycle.UpdateModelValuesExecutor.execute(UpdateModelValuesExecutor.java:38)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at uk.ac.exeter.QuinCe.web.User.AuthenticatedFilter.doFilter(AuthenticatedFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.ELException: Error reading [nrt] on type [uk.ac.exeter.QuinCe.web.datasets.plotPage.ManualQC.ManualQcBean]
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:98)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.parser.AstNot.getValue(AstNot.java:43)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96)
	... 42 more
Caused by: java.lang.NullPointerException
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageBean.isNrt(PlotPageBean.java:758)
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
	... 48 more
```

**Comment by squaregoldfish** [comment]
This doesn't seem to be happening any more.

**Comment by squaregoldfish** [comment]
This doesn't seem to be happening any more.
