### ISSUE TITLE
Error calculating calibrated values for Simon Stevin

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1816]
Data Reduction - error: Error in value calculator for SensorType Sensor Type: xH₂O (with standards): Error while calculating calibrated value
```
uk.ac.exeter.QuinCe.data.Dataset.DataReduction.ValueCalculatorException: Error in value calculator for SensorType Sensor Type: xH₂O (with standards): Error while calculating calibrated value
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.xCO2InGasWithStandardsCalculator.calibrate(xCO2InGasWithStandardsCalculator.java:281)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.xCO2InGasWithStandardsCalculator.dryingCalculation(xCO2InGasWithStandardsCalculator.java:124)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.xCO2InGasWithStandardsCalculator.calculateValue(xCO2InGasWithStandardsCalculator.java:72)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.ValueCalculators.calculateValue(ValueCalculators.java:34)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.MeasurementValues.getValue(MeasurementValues.java:65)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.UnderwayAtmosphericPco2Reducer.doCalculation(UnderwayAtmosphericPco2Reducer.java:44)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.DataReducer.performDataReduction(DataReducer.java:94)
at uk.ac.exeter.QuinCe.jobs.files.DataReductionJob.execute(DataReductionJob.java:169)
at uk.ac.exeter.QuinCe.jobs.JobThread.run(JobThread.java:86)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -55917
at java.util.ArrayList.elementData(ArrayList.java:422)
at java.util.ArrayList.get(ArrayList.java:435)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.xCO2InGasWithStandardsCalculator.getPostCalibrationValue(xCO2InGasWithStandardsCalculator.java:374)
at uk.ac.exeter.QuinCe.data.Dataset.DataReduction.xCO2InGasWithStandardsCalculator.calibrate(xCO2InGasWithStandardsCalculator.java:256)
... 8 more
```

**Comment by squaregoldfish** [comment]
This is an intermittent problem. Seems to be related to the issue found in #1790.
