### ISSUE TITLE
Standards QC page doesn't work if no xH₂O column defined

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#1844]
The gas standards QC page does not work if the optional xH₂O column has not been defined as part of the instrument.

```java
java.lang.Exception: Empty column group 'xH₂O (with standards)'
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.validateColumnHeadings(PlotPageData.java:405)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.buildColumnHeadingsJson(PlotPageData.java:326)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.getColumnHeadingsJson(PlotPageData.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:360)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:67)
	at javax.faces.component.UIInput.getValue(UIInput.java:151)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getValue(RendererUtils.java:486)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getStringValue(RendererUtils.java:324)
	at org.apache.myfaces.renderkit.html.HtmlHiddenRenderer.encodeEnd(HtmlHiddenRenderer.java:60)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.processRenderComponent(PartialViewContextImpl.java:826)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:787)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1016)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:539)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at uk.ac.exeter.QuinCe.web.User.AuthenticatedFilter.doFilter(AuthenticatedFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: Empty column group 'xH₂O (with standards)'
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.validateColumnHeadings(PlotPageData.java:405)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.buildColumnHeadingsJson(PlotPageData.java:326)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.getExtendedColumnHeadingsJson(PlotPageData.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:360)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:67)
	at javax.faces.component.UIInput.getValue(UIInput.java:151)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getValue(RendererUtils.java:486)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getStringValue(RendererUtils.java:324)
	at org.apache.myfaces.renderkit.html.HtmlHiddenRenderer.encodeEnd(HtmlHiddenRenderer.java:60)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.processRenderComponent(PartialViewContextImpl.java:826)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:787)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1016)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:539)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at uk.ac.exeter.QuinCe.web.User.AuthenticatedFilter.doFilter(AuthenticatedFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: Empty column group 'xH₂O (with standards)'
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.validateColumnHeadings(PlotPageData.java:405)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.buildColumnHeadingsJson(PlotPageData.java:326)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.getColumnHeadingsJson(PlotPageData.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:360)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:67)
	at javax.faces.component.UIInput.getValue(UIInput.java:151)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getValue(RendererUtils.java:486)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getStringValue(RendererUtils.java:324)
	at org.apache.myfaces.renderkit.html.HtmlHiddenRenderer.encodeEnd(HtmlHiddenRenderer.java:60)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.processRenderComponent(PartialViewContextImpl.java:826)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:787)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1016)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:539)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at uk.ac.exeter.QuinCe.web.User.AuthenticatedFilter.doFilter(AuthenticatedFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Exception: Empty column group 'xH₂O (with standards)'
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.validateColumnHeadings(PlotPageData.java:405)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.buildColumnHeadingsJson(PlotPageData.java:326)
	at uk.ac.exeter.QuinCe.web.datasets.plotPage.PlotPageData.getExtendedColumnHeadingsJson(PlotPageData.java:312)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:360)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:67)
	at javax.faces.component.UIInput.getValue(UIInput.java:151)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getValue(RendererUtils.java:486)
	at org.apache.myfaces.shared.renderkit.RendererUtils.getStringValue(RendererUtils.java:324)
	at org.apache.myfaces.renderkit.html.HtmlHiddenRenderer.encodeEnd(HtmlHiddenRenderer.java:60)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.processRenderComponent(PartialViewContextImpl.java:826)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:787)
	at org.apache.myfaces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:213)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1016)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:539)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
	at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
	at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at uk.ac.exeter.QuinCe.web.User.AuthenticatedFilter.doFilter(AuthenticatedFilter.java:91)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MarenKK** [comment]
Should be fixed as part of #1664
