### ISSUE TITLE
CONTROS algorithm updates

### ISSUE THREAD

**Issue by squaregoldfish** [BjerknesClimateDataCentre/QuinCe#2553]
Find and destroy

This issue will also be used for updating the Contros algorithm itself in conversation with 4H-Jena. Incorporates the following issues:
#2139 

Tasks:
- [x] Ensure that continuous mode (with and without post-calibration parameters) matches code published by Nadja
- [x] Make sure that calculation without pre-calibration parameters is not possible
    - Same logic as no gas standards
    - Assume that this is a universal requirement
- [x] If only pre-calibration is available, use that as a static value instead of interpolating between pre- and post- calibration values
- [x] Ensure that calibration values are included in export manifest (#2375)
- [x] ~~Calibration of zeros on separate screen a la gas standards~~ Not needed, I think
- [x] Add options for sleep mode running, where only the preceding or following zero run (depending on firmware version) is used instead of interpolating
- [x] Figure out export logic for datasets without post-calibration - how should they be marked?
    - Flag as 1 (equivalent to WOCE CTD not calibrated)
    - Add message to export page (and one for uncompleted manual QC)
    - Generic system for this kind of export-time check
      - May not be needed
- [x] Test non-zero zero flushing time
- [x] Check possible Runtime bug with Nadja and Vlad - we're multiplying by `Runtime` and not `Runtime - Runtime_prior` for the `k` interps.
- [x] Tests for data reducer
    - Data Reducer
    - Measurement Locator
    - ~~Data Reduction QC (missing post calibration sets status)~~ Too hard for now. I am lazy.
- [x] Add SST for fCO2
- [ ] New humidity-based algorithm

**Comment by glncstll** [comment]
it seems that the query you ask for the mysql database is wrong, you ask for:
SELECT date, value FROM sensor_values WHERE dataset_id = 6 AND file_column IN () ORDER BY date ASC;
and it is wrong
but if you ask for:
SELECT date, value FROM sensor_values WHERE dataset_id = 6 AND file_column ORDER BY date ASC;
without IN () after file_column in the query string it works
also in the error message is written there is error in the sql syntax:
[uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	[uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘) ORDER BY date ASC’ at line 1
	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:568)
	org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	jdk.proxy2/jdk.proxy2.$Proxy15.executeQuery(Unknown Source)
	[uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1145)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobFailedException: Job ID 11 failed
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:294)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: [uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	[uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobFailedException: Job ID 11 failed
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:294)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: [uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	at [uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	... 1 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘) ORDER BY date ASC’ at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy2/jdk.proxy2.$Proxy15.executeQuery(Unknown Source)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1145)
	... 2 more
[uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	[uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘) ORDER BY date ASC’ at line 1
	com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:568)
	org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	jdk.proxy2/jdk.proxy2.$Proxy15.executeQuery(Unknown Source)
	[uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1145)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobFailedException: Job ID 11 failed
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:294)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: [uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	[uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
[uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobFailedException: Job ID 11 failed
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:294)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: [uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	at [uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	... 1 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘) ORDER BY date ASC’ at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at jdk.internal.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy2/jdk.proxy2.$Proxy15.executeQuery(Unknown Source)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1145)
	... 2 more


the error is caused in the DataSetDataDB.java file see where I have put breakpoints


![Schermata 2022-11-10 alle 12 36 14](https://user-images.githubusercontent.com/20475966/201092552-fa50c6aa-77de-4e0d-9acc-2caba34d3a72.png)

**Comment by squaregoldfish** [comment]
There's an error during Auto QC that doesn't prevent the dataset being processed, but should nevertheless be eliminated:

```
Sensor Quality Control - error: Error while getting run type periods
[uk.ac](http://uk.ac/).exeter.QuinCe.utils.DatabaseException: Error while getting run type periods
	at [uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1152)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.files.AutoQCJob.execute(AutoQCJob.java:166)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.jobs.JobThread.run(JobThread.java:89)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘) ORDER BY date ASC’ at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
	at jdk.internal.reflect.GeneratedMethodAccessor81.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at jdk.proxy2/jdk.proxy2.$Proxy15.executeQuery(Unknown Source)
	at [uk.ac](http://uk.ac/).exeter.QuinCe.data.Dataset.DataSetDataDB.getRunTypePeriods(DataSetDataDB.java:1145)
	... 2 more
```

**Comment by squaregoldfish** [comment]
For datasets without post-calibration, there's a few things to note:

- NRT is OK - it's all "questionable" anyway
- Should not be allowed to Submit
- Exported files need something in manifest and data
  - Tobias suggests Argo notation of R = realtime (no QC) A = automatic QC and D = Delayed mode (L2)
  - Alternatively (currently preferred) use 1 as Not Calibrated (https://exchange-format.readthedocs.io/en/latest/quality.html)

**Comment by squaregoldfish** [comment]
Flag order (most to least)

- Lookup (-200)
- Flushing (-100)
- Needed (-10)
- Bad (4)
- Questionable(3)
- **NEW** Not Calibrated (1)
- Good (2) / Assumed Good (-2)
- No QC (0)

**Comment by squaregoldfish** [comment]
There's an update to the CONTROS algorithm on the way that uses more columns from the data files.

**Comment by squaregoldfish** [comment]
OK, so I did the SST correction stuff wrong.

New sensors can have a T_membrane, which we should use to correct to SST if it's in the data files. So we need to add a question to the CONTROS variable of "Do you have T_membrane sensor?" and then apply that if the user says yes.

**Comment by squaregoldfish** [comment]
We're going to publish what we have, and update the algorithm in future if needed.

**Comment by squaregoldfish** [comment]
The new algorithm is delayed. We will release with the current algorithm, and any updates will be handled as separate issues.
