### ISSUE TITLE
View expired exception on dataset_list page

### ISSUE THREAD

**Issue by jonasfh** [BjerknesClimateDataCentre/QuinCe#915]
There is an issue seems to be related to loading an empty dataset list. When logging in and displaying an empty list, the following error is thrown as the page refreshes: 

> javax.faces.application.ViewExpiredException: /dataset/dataset_list.xhtml - No saved view state could be found for the view identifier: /dataset/dataset_list.xhtml
>>	at org.apache.myfaces.lifecycle.RestoreViewExecutor.execute(RestoreViewExecutor.java:183)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at uk.ac.exeter.QuinCe.web.User.AuthenticatedFilter.doFilter(AuthenticatedFilter.java:85)
        ...
	at java.lang.Thread.run(Thread.java:748)

**Comment by jonasfh** [comment]
This issue happens when you have the datase-list window open (which pings the server every 10 seconds), and restarts the server. The issue is not likely to be an actual problem in production.
